[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[features]
debug = []

[dependencies]
rayon = "1.11.0"
rustc-hash = "2.1.1"
simple-tqdm = { version = "0.2.0", features = ["rayon"] }
